start: (winding | markdown)+

winding: space_winding | inline_winding
space_winding: "--\n" IDENTIFIER ":" attributes "\n--\n" content?
inline_winding: "@" IDENTIFIER ":" attributes "\n" content?

content: (winding | markdown)+

markdown: (image | TEXT)+

attributes: (IDENTIFIER ("," IDENTIFIER)*)?

image: "![" IDENTIFIER "]" "(" URI ")"

IDENTIFIER: /!?[A-Za-z][A-Za-z0-9_.-]*/
URI: /[^\)\n]+/
TEXT: /(?:(?!@\w+:|--|!\[).)*\n+/ 
    
%ignore /[ \t]+/
%ignore "\r"  